r"""
Per-orbit apsidal precession of S2.

Two physically distinct contributions are computed and reported
separately, then combined:

1. Relativistic (Schwarzschild, 1PN, prograde) precession from the
   central mass M_c:
       Delta_phi_GR = 6 pi G M_c / (c^2 a (1 - e^2))     [rad / orbit]
   (This is the GRAVITY-2018/2020 detected Schwarzschild precession of
   S2, ~ 12 arcmin/orbit for a point mass.)

2. Newtonian (retrograde) precession produced by the *extended* mass
   distribution M(r) interior to the orbit.  A diffuse mass makes the
   potential softer than Keplerian, so the orbit precesses backwards.
   We compute it from the exact apsidal angle of the orbit in the
   spherical potential generated by the enclosed-mass profile M(r):

       Delta_phi_orbit = 2 * integral_{r_peri}^{r_apo}
                              (L / r^2) / sqrt(2(E - Phi_eff(r))) dr  -  2 pi

   with Phi(r) from   dPhi/dr = G M(<r) / r^2 ,  and
   L, E fixed by the turning-point conditions at r_peri and r_apo.

The net precession reported is Delta_phi_GR + Delta_phi_mass, where
Delta_phi_mass = Delta_phi_orbit evaluated with the diffuse component
only (the GR piece carries the core monopole separately, to avoid
double counting the Keplerian part).

UNITS: SI inputs, output in radians per orbit (with arcsec helper).
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.integrate import quad
from scipy.optimize import brentq

from .constants import C_LIGHT, G_NEWTON
from .rar_tov_solver import Profile

RAD_TO_ARCSEC = 180.0 / np.pi * 3600.0
RAD_TO_ARCMIN = 180.0 / np.pi * 60.0


@dataclass(frozen=True)
class Precession:
    delta_phi_gr_rad: float        # Schwarzschild prograde
    delta_phi_mass_rad: float      # extended-mass retrograde (<=0)
    delta_phi_total_rad: float
    delta_phi_total_arcmin: float


def schwarzschild_precession_rad(M_core_kg: float, a_m: float, e: float) -> float:
    """6 pi G M / (c^2 a (1-e^2))  [rad/orbit]."""
    return 6.0 * np.pi * G_NEWTON * M_core_kg / (C_LIGHT**2 * a_m * (1.0 - e * e))


def _enclosed_mass_func(profile: Profile, subtract_core_kg: float = 0.0):
    """Return M_diffuse(<r) = M(<r) - core, clipped at 0."""
    def M(r):
        return max(float(profile.enclosed_mass_kg(r)) - subtract_core_kg, 0.0)
    return M


def mass_precession_rad(profile: Profile, a_m: float, e: float,
                        M_core_kg: float) -> float:
    """Retrograde precession from the diffuse mass interior to S2.

    Treats the central monopole M_core as a point mass (its Keplerian part
    yields zero precession by construction) and adds the perturbation from
    the diffuse enclosed mass M_diff(<r).  Computed via the exact apsidal
    integral in the resulting spherical potential.
    """
    r_peri = a_m * (1.0 - e)
    r_apo = a_m * (1.0 + e)

    M_diff = _enclosed_mass_func(profile, subtract_core_kg=M_core_kg)

    # Total potential: point-core + diffuse shell contributions.
    #   Phi(r) = -G M_core / r  +  Phi_diff(r),  dPhi_diff/dr = G M_diff(<r)/r^2
    # We only need Phi up to an additive constant; integrate from r_peri.
    def dPhi(r):
        return G_NEWTON * (M_core_kg + M_diff(r)) / r**2

    def Phi(r):
        val, _ = quad(dPhi, r_peri, r, limit=100)
        return val  # Phi(r_peri) = 0 reference

    Phi_peri = 0.0
    Phi_apo = Phi(r_apo)

    # Specific energy E and angular momentum L from turning points:
    #   E = Phi + L^2/(2 r^2)  at both r_peri and r_apo  (radial velocity = 0)
    # Solve the 2x2 system:
    #   E - L^2/(2 r_peri^2) = Phi_peri
    #   E - L^2/(2 r_apo^2)  = Phi_apo
    inv = 0.5 * (1.0 / r_peri**2 - 1.0 / r_apo**2)
    L2 = (Phi_apo - Phi_peri) / inv
    if L2 <= 0:
        return 0.0
    L = np.sqrt(L2)
    E = Phi_peri + L2 / (2.0 * r_peri**2)

    def radial(r):
        return 2.0 * (E - Phi(r)) - L2 / r**2

    # apsidal angle integral; guard the (integrable) sqrt singularities
    def integrand(r):
        val = radial(r)
        if val <= 0:
            return 0.0
        return (L / r**2) / np.sqrt(val)

    eps = 1e-6 * (r_apo - r_peri)
    apsidal, _ = quad(integrand, r_peri + eps, r_apo - eps, limit=200)
    delta_phi = 2.0 * apsidal - 2.0 * np.pi
    return float(delta_phi)


def precession_per_orbit(profile: Profile, a_m: float, e: float,
                         M_core_kg: float) -> Precession:
    gr = schwarzschild_precession_rad(M_core_kg, a_m, e)
    mass = mass_precession_rad(profile, a_m, e, M_core_kg)
    total = gr + mass
    return Precession(
        delta_phi_gr_rad=gr,
        delta_phi_mass_rad=mass,
        delta_phi_total_rad=total,
        delta_phi_total_arcmin=total * RAD_TO_ARCMIN,
    )
